# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=140)),
                ('city', models.CharField(default='', max_length=50)),
                ('website', models.URLField(default='')),
                ('phone', models.CharField(default='', max_length=11)),
                ('image', models.ImageField(default='profile_image/19905311_469038166767229_3881908191928370159_n_oScytAS.jpg', upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
