# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='websity',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_image/19905311_469038166767229_3881908191928370159_n_oScytAS.jpg', upload_to='profile_image'),
        ),
    ]
