# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='from_user',
            new_name='user',
        ),
    ]
